---

- hosts: all
  become: true
  tasks:
  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache packages
    apt:
      name: apache2
      state: latest

  - name: php support
    apt:
      name: libapache2-mod-php
      state: latest
